# Generated by Django 2.1.2 on 2019-08-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_rp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCPolling_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_id', models.IntegerField()),
                ('access_token', models.CharField(blank=True, max_length=240)),
                ('id_token', models.TextField(blank=True, max_length=400)),
                ('refresh_token', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(default='KO', max_length=22)),
            ],
        ),
    ]
